name: hg-photo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1061374784912914
  lightness: 0.5342269244138151
  saturation: 0.11430479073897004
  rhythmicContrast: 0.04069441859610379
purpose: []
