name: hg-photo
favicon: null
layout_spectrum: 0.24307
typography_spectrum: 0.59782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececec'
    - '#2d2d2d'
    - '#4b4b4b'
    - '#111111'
    - '#868686'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
