name: hg-photo
favicon: null
layout_spectrum: 0.87997
typography_spectrum: 0.31028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76aecd'
    - '#d2dbe1'
    - '#316586'
    - '#151110'
    - '#ce8951'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
